version: "3.9"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve
    restart: unless-stopped
    ports:
      - "5212:5212"
    volumes:
      - data:/data
      - temp_data:/data/aria2
    depends_on:
      - aria2
  aria2:
    container_name: aria2
    image: p3terx/aria2-pro
    restart: unless-stopped
    environment:
      - RPC_SECRET=unsafe
      - RPC_PORT=6800
    volumes:
      - ./aria2/config:/config
      - temp_data:/data
volumes:
  data:
  temp_data: